const router = require('express').Router()
const routerMedicine = require('./routerMedicine')
const routerDoctor = require('./routerDoctor')
const routerHospital = require('./routerHospital')
const routerHospitalAPI = require('./routerHospitalAPI')
const routerCovid = require('./routerCovid')
const routerProvince = require('./routerProvince')
const routerUser = require('./routerUser')
const routerSpecialist = require('./routerSpecialist')
const routerNodeMailer = require('./routerNodeMailer')
const errorHandler = require('../middlewares/errorHandler')

router.use('/medicines', routerMedicine)
router.use('/doctors', routerDoctor)
router.use('/hospitals', routerHospital)
router.use('/api', routerHospitalAPI)
router.use('/covid19/stats', routerCovid)
router.use('/provinces', routerProvince)
router.use('/users', routerUser)
router.use('/specialists', routerSpecialist)
router.use('/nodemailer', routerNodeMailer)

router.use(errorHandler)

module.exports = router